server:
  port: 6080
  http2:
    enabled: true
  undertow:
    threads:
      io: 16
      worker: 256
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: user-server
  profiles:
    active: dev
  cloud:
    bus:
      refresh:
        enabled: true

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: false



ribbon:
  eureka:
    enabled: true


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #  typeAliasesPackage: com.riversking.user.entity
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话
    call-setters-on-nulls: false


logging:
  level:
    com.rivers: debug
  #  spring-admin 读取应用的日志 关键
  file:
    path: ./logs/${spring.application.name}/all.log
    name: ./logs/${spring.application.name}/all.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      enabled: true
    loggers:
      enabled: true
    bus-refresh:
      enabled: true

ignore:
  urls:
    - /actuator/**
    - /user/login
    - /user/info
