spring:
  application:
    name: eureka-server
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 8761

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://139.9.206.164:8761/eureka/,http://1.15.229.197:8761/eureka/
  server:
    enable-self-preservation: false
    peer-node-connect-timeout-ms: 200


management:
  endpoint:
    shutdown:
      enabled: true

