server:
  port:
    9080

spring:
  application:
    name: oauth-server
  profiles:
    active: dev
  cloud:
    bus:
      refresh:
        enabled: true
  main:
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.riversking.oauth.entity
  global-config:
    #    id: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    #    db-column-underline: false
    #    refresh-mapper: true
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话

# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: false

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false


logging:
  level:
    com.riversking: debug
  file:
    name: ./logs/${spring.application.name}/all.log
    path: D:\project\timer\logs\oauth-server\all.log


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    bus-refresh:
      enabled: true

